#!/usr/bin/env python3
"""
generate_opco_playbooks.py — one-pager playbook per OPCO, generated from the
registries + live Neo4j capability graph (not hand-written).

For each of the 18 OPCOs:
  - venture count + list (registries/ventures.csv, opco_venture_map.csv)
  - capabilities already available (Neo4j: repos IMPLEMENTS capabilities NEEDS by
    ventures in this OPCO)
  - top 5 priority ventures = most of their needed capabilities already covered by
    an existing repo (buildability score), tie-break by stage=planned first

Output: WORLDWIDEBRO-OS/03-PORTFOLIO/opcos/<OPCO>/PLAYBOOK.md (one file, idempotent —
reruns overwrite cleanly)

Usage: python3 generate_opco_playbooks.py
"""
import csv
import os
from neo4j import GraphDatabase
from os_env import NEO4J_URI, NEO4J_AUTH

DOCS = "/Users/acebless/Documents"
REG = f"{DOCS}/WORLDWIDEBRO-OS/08-DATA/registries"
OPCO_DIR = f"{DOCS}/WORLDWIDEBRO-OS/03-PORTFOLIO/opcos"


def load_ventures():
    with open(f"{REG}/ventures.csv") as f:
        return {row["venture_id"]: row for row in csv.DictReader(f)}


def load_opcos():
    with open(f"{REG}/opcos.csv") as f:
        return list(csv.DictReader(f))


def opco_folder_name(opco_id):
    # Use the registry's own opco_id as the folder name, unchanged. The pre-existing
    # opcos/ folder tree was built against an OLDER, DIFFERENT 18-sector scheme
    # (AGRICULTURE, HOSPITALITY, TRANSPORTATION, INVESTMENT, ENERGY, HEALTHCARE,
    # MARKETPLACE, RETAIL, MANUFACTURING, STAFFING, MEDIA...) that only partially
    # overlaps registries/opcos.csv's current 18 (E-COMMERCE, SOFTWARE-TECHNOLOGY,
    # EDUCATION-TRAINING, FOOD-HOSPITALITY, LOGISTICS-TRANSPORT, etc). Forcing a
    # name-guess mapping between the two caused a silent overwrite bug (two distinct
    # OPCOs collapsed into one folder). Not reconciling that here — just write each
    # of the 18 CURRENT opco_ids to its own folder, verbatim, no guessing.
    return opco_id


def main():
    ventures = load_ventures()
    opcos = load_opcos()

    driver = GraphDatabase.driver(NEO4J_URI, auth=NEO4J_AUTH)
    combined = ["# OpCo Playbooks — Master Index\n",
                "Generated from registries/ventures.csv + opco_venture_map.csv + Neo4j capability graph.\n"]

    with driver.session() as session:
        for opco in opcos:
            opco_id = opco["opco_id"]
            v_ids = [vid for vid, v in ventures.items() if v["opco"] == opco_id]
            if not v_ids:
                continue

            # buildability score per venture: what FRACTION of the capabilities this
            # venture needs already have at least one implementing repo (raw repo
            # COUNT is meaningless here — generic capabilities like "api"/"llm" are
            # implemented by hundreds of repos, which drowns out the signal)
            rows = session.run(
                "UNWIND $vids AS vid "
                "MATCH (v:Venture {id: vid})-[:NEEDS]->(c:Capability) "
                "OPTIONAL MATCH (c)<-[:IMPLEMENTS]-(r:Repo) "
                "WITH vid, c.name AS cap, count(DISTINCT r) > 0 AS has_repo "
                "RETURN vid, count(cap) AS needed, sum(CASE WHEN has_repo THEN 1 ELSE 0 END) AS covered, "
                "collect(DISTINCT cap)[0..6] AS caps",
                vids=v_ids)
            coverage = {row["vid"]: (row["covered"], row["needed"], row["caps"]) for row in rows}

            scored = []
            for vid in v_ids:
                covered, needed, caps = coverage.get(vid, (0, 0, []))
                ratio = covered / needed if needed else 0.0
                scored.append((ratio, covered, needed, vid, caps))
            scored.sort(key=lambda x: (-x[0], -x[2], x[3]))

            all_caps = sorted({c for _, _, _, _, caps in scored for c in caps})
            top5 = scored[:5]

            folder = opco_folder_name(opco_id)
            out_dir = f"{OPCO_DIR}/{folder}"
            os.makedirs(out_dir, exist_ok=True)

            lines = [f"# {opco['sector_label']} — OpCo Playbook\n",
                     f"_Generated by generate_opco_playbooks.py from live registry + graph data._\n",
                     f"## Ventures ({opco['venture_count']})\n"]
            for vid in sorted(v_ids)[:20]:
                lines.append(f"- {vid} — {ventures[vid]['name']}")
            if len(v_ids) > 20:
                lines.append(f"- ...and {len(v_ids) - 20} more (see registries/opco_venture_map.csv)")

            lines.append("\n## Priority ventures (ranked by capability coverage: needed caps that already have an implementing repo)\n")
            for i, (ratio, covered, needed, vid, caps) in enumerate(top5, 1):
                name = ventures[vid]["name"]
                cap_str = ", ".join(caps) if caps else "no capability data yet"
                lines.append(f"{i}. **{vid}** ({name}) — {covered}/{needed} capabilities covered "
                              f"({ratio:.0%}), e.g. {cap_str}")

            lines.append("\n## Capabilities available in this sector\n")
            lines.append(", ".join(all_caps) if all_caps else "none mapped yet")

            lines.append("\n## First move\n")
            if top5 and top5[0][1] > 0:
                lines.append(f"Launch **{top5[0][3]}** first — {top5[0][1]}/{top5[0][2]} needed "
                              f"capabilities already have an implementing repo.")
            else:
                lines.append("No venture in this OPCO has repo coverage yet — needs a capability "
                              "mapping pass before a build order can be picked.")

            content = "\n".join(lines) + "\n"
            with open(f"{out_dir}/PLAYBOOK.md", "w") as f:
                f.write(content)

            print(f"{opco_id:25s} -> {out_dir}/PLAYBOOK.md ({len(v_ids)} ventures, "
                  f"top coverage={top5[0][0]:.0%})" if top5 else f"{opco_id}: no ventures")

            combined.append(f"\n---\n\n{content}")

    driver.close()

    with open(f"{OPCO_DIR}/MASTER-PLAYBOOK.md", "w") as f:
        f.write("\n".join(combined))
    print(f"\nCombined -> {OPCO_DIR}/MASTER-PLAYBOOK.md")


if __name__ == "__main__":
    main()
