apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    host: postgres
    port: 5432
    database: twenty
    user: postgres
    secureJsonData:
      password: postgres
