apiVersion: 1

datasources:
  - name: DuckDB
    type: postgres
    access: proxy
    orgId: 1
    url: localhost:5432
    password: ''
    user: ''
    database: worldwidebro_os.duckdb
    basicAuth: false
    isDefault: true
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1200
      tlsSkipVerify: false
    readOnly: false
