worldwidebro_analytics:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5433
      dbname: company_brain
      schema: analytics_dev
      threads: 4
      keepalives_idle: 0

    staging:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST_STAGING') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: company_brain_staging
      schema: analytics_staging
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST_PROD') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: company_brain_prod
      schema: analytics
      threads: 8

  target: dev
