// WORLDWIDEBRO-OS Capability Graph Initialization
MATCH (n) DETACH DELETE n;

// 1. Create Repository Nodes
CREATE (:Repository {name: 'unknown', url: '', category: '', purpose: '', status: 'planned'});
CREATE (:Repository {name: 'awesome-gemini-cli', url: 'https://github.com/Piebald-AI/awesome-gemini-cli', category: 'Awesome Lists', purpose: 'Curated index of Gemini CLI extensions and resources', status: 'active'});
CREATE (:Repository {name: 'awesome-gemini-cli-dtunai', url: 'https://github.com/dtunai/awesome-gemini-cli', category: 'Awesome Lists', purpose: 'Collection of tutorials and examples for Gemini CLI', status: 'active'});
CREATE (:Repository {name: 'awesome-cli-coding-agents', url: 'https://github.com/bradAGI/awesome-cli-coding-agents', category: 'Awesome Lists', purpose: 'Benchmark comparison of terminal agents (Claude Code, Gemini CLI, etc.)', status: 'active'});
CREATE (:Repository {name: 'gemini-api-cookbook', url: 'https://github.com/google-gemini/cookbook', category: 'Cookbooks', purpose: 'Official hands-on tutorial and example code for Gemini API', status: 'active'});
CREATE (:Repository {name: 'gemini-cli-demo-cookbook', url: 'https://github.com/ptone/cli-demo-cookbook', category: 'Cookbooks', purpose: 'Developer showcase of common terminal automation tasks', status: 'active'});
CREATE (:Repository {name: 'gemini-cli-tips', url: 'https://github.com/addyosmani/gemini-cli-tips', category: 'Best Practices', purpose: '30 pro-tips covering agentic coding patterns', status: 'active'});
CREATE (:Repository {name: 'gemini-cli-best-practice', url: 'https://github.com/shanraisshan/gemini-cli-best-practice', category: 'Best Practices', purpose: 'Guides on moving from vibe coding to structured GEMINI.md templates', status: 'active'});
CREATE (:Repository {name: 'gemini-skills', url: 'https://github.com/google-gemini/gemini-skills', category: 'Skills', purpose: 'Official skills for adding lightweight capabilities to Gemini agents', status: 'active'});
CREATE (:Repository {name: 'agent-skills', url: 'https://github.com/addyosmani/agent-skills', category: 'Skills', purpose: 'Skills system that auto-discovers SKILL.md rules files', status: 'active'});
CREATE (:Repository {name: 'agentic-awesome-skills', url: 'https://github.com/sickn33/agentic-awesome-skills', category: 'Skills', purpose: 'Community registry of agentic skills and modular workflows', status: 'active'});
CREATE (:Repository {name: 'mcp-openai-bridge', url: 'https://github.com/Intelligent-Internet/gemini-cli-mcp-openai-bridge', category: 'MCP Ecosystem', purpose: 'Hub connecting Gemini CLI to external tools via Model Context Protocol', status: 'active'});
CREATE (:Repository {name: 'mcp-toolbox', url: 'https://github.com/gemini-cli-extensions/mcp-toolbox', category: 'MCP Ecosystem', purpose: 'Create custom MCP servers with secure, verified tools', status: 'active'});
CREATE (:Repository {name: 'workspace-extension', url: 'https://github.com/gemini-cli-extensions/workspace', category: 'Extensions', purpose: 'Integrates Google Workspace (Docs, Sheets, Drive) with Gemini CLI', status: 'active'});
CREATE (:Repository {name: 'conductor-extension', url: 'https://github.com/gemini-cli-extensions/conductor', category: 'Extensions', purpose: 'Context-driven development and proactive project management', status: 'active'});
CREATE (:Repository {name: 'code-review-extension', url: 'https://github.com/gemini-cli-extensions/code-review', category: 'Extensions', purpose: 'Autonomous reviewer checking Git branches and PRs', status: 'active'});
CREATE (:Repository {name: 'rtk', url: 'https://github.com/rtk-airtk', category: 'Token Optimization', purpose: 'YAML filter proxy reducing input token counts by 60-90%', status: 'active'});
CREATE (:Repository {name: 'run-gemini-cli', url: 'https://github.com/google-github-actions/run-gemini-cli', category: 'GitHub Actions', purpose: 'GitHub Action for issue triage, reviews, and codebase scans', status: 'active'});
CREATE (:Repository {name: 'gpt4all', url: 'https://github.com/nomic-ai/gpt4all', category: 'Local AI Runtime', purpose: 'Running lightweight LLMs locally on edge and desktop environments', status: 'active'});
CREATE (:Repository {name: 'localai', url: 'https://github.com/mudler/LocalAI', category: 'Local AI Runtime', purpose: 'OpenAI-compatible local API server wrapping models, speech, and vision', status: 'active'});
CREATE (:Repository {name: 'lemonade-sdk', url: 'https://github.com/lemonade-sdk/lemonade', category: 'Local AI Runtime', purpose: 'NPU and GPU acceleration layer for local models on hardware', status: 'planned'});
CREATE (:Repository {name: 'codegraph', url: 'https://github.com/colbymchenry/codegraph', category: 'Code Intelligence', purpose: 'Building local codebase graphs mapping directories and symbols', status: 'planned'});
CREATE (:Repository {name: 'gitnexus', url: 'https://github.com/abhigyanpatwari/GitNexus', category: 'Code Intelligence', purpose: 'Scanning repository graphs and mapping dependency files', status: 'active'});
CREATE (:Repository {name: 'socraticode', url: 'https://github.com/giancarloerra/SocratiCode', category: 'Code Intelligence', purpose: 'Semantic codebase impact explorer and repository context mapper', status: 'planned'});
CREATE (:Repository {name: 'grepai', url: 'https://github.com/yoanbernabeu/grepai', category: 'Code Intelligence', purpose: 'Call-graph indexer and rapid semantic grep search', status: 'planned'});
CREATE (:Repository {name: 'openhuman', url: 'https://github.com/tinyhumansai/openhuman', category: 'Agent Desktop', purpose: 'Personal super-intelligence desktop orchestration framework', status: 'active'});
CREATE (:Repository {name: 'aionui', url: 'https://github.com/iOfficeAI/AionUi', category: 'Agent Desktop', purpose: 'Desktop launcher integrating Claude Code, Codex, and Gemini CLI', status: 'planned'});
CREATE (:Repository {name: 'eigent', url: 'https://github.com/eigent-ai/eigent', category: 'Agent Desktop', purpose: 'AI employee cowork desktop interface', status: 'planned'});
CREATE (:Repository {name: 'agenticseek', url: 'https://github.com/Fosowl/agenticSeek', category: 'Agent Desktop', purpose: 'Fully autonomous web browsing, reasoning, and coding agent', status: 'active'});
CREATE (:Repository {name: 'dyad', url: 'https://github.com/dyad-sh/dyad', category: 'App Factory', purpose: 'Low-code application builder compiling systems from prompts', status: 'active'});
CREATE (:Repository {name: 'claudable', url: 'https://github.com/opactorai/Claudable', category: 'App Factory', purpose: 'Autonomous website builder CLI agent', status: 'planned'});
CREATE (:Repository {name: 'camunda', url: 'https://github.com/camunda/camunda', category: 'Automation', purpose: 'Enterprise BPMN process engine orchestrating complex tasks', status: 'active'});
CREATE (:Repository {name: 'localstack', url: 'https://github.com/localstack/localstack', category: 'Infrastructure', purpose: 'Offline AWS cloud simulation (Lambda, S3, DynamoDB, SQS)', status: 'active'});
CREATE (:Repository {name: 'metatron', url: 'https://github.com/AgriciDaniel/METATRON', category: 'Security', purpose: 'AI penetration testing scan helper checking credentials and ports', status: 'planned'});
CREATE (:Repository {name: 'obsidian-second-brain', url: 'https://github.com/eugeniughelbur/obsidian-second-brain', category: 'Data Memory', purpose: 'Synchronizes personal wikis and obsidian vaults into agent tools', status: 'active'});
CREATE (:Repository {name: 'meetily', url: 'https://github.com/Zackriya-Solutions/meetily', category: 'Voice Intelligence', purpose: 'Meeting assistant generating audio transcription and summaries', status: 'planned'});
CREATE (:Repository {name: 'natively-cluely-ai-assistant', url: 'https://github.com/Natively-AI-assistant/natively-cluely-ai-assistant', category: 'Voice Intelligence', purpose: 'Real-time meeting notes compiler and speaker diarization', status: 'planned'});
CREATE (:Repository {name: 'pindrop', url: 'https://github.com/watzon/pindrop', category: 'Voice Intelligence', purpose: 'macOS Whisper dictation client forwarding to CLI prompts', status: 'active'});
CREATE (:Repository {name: 'frigate', url: 'https://github.com/blakeblackshear/frigate', category: 'Computer Vision', purpose: 'Local real-time NVR object detection mapping facilities', status: 'planned'});
CREATE (:Repository {name: 'vert', url: 'https://github.com/VERT-sh/VERT', category: 'Computer Vision', purpose: 'Offline file format and media conversion processor', status: 'active'});
CREATE (:Repository {name: 'langgraph', url: 'https://github.com/langchain-ai/langgraph', category: 'Agent Frameworks', purpose: 'Stateful multi-actor orchestration supporting cyclic graphs', status: 'active'});
CREATE (:Repository {name: 'crewai', url: 'https://github.com/crewAIInc/crewAI', category: 'Agent Frameworks', purpose: 'Multi-agent team assembly and task allocation', status: 'active'});
CREATE (:Repository {name: 'autogen', url: 'https://github.com/microsoft/autogen', category: 'Agent Frameworks', purpose: 'Conversational multi-agent framework mapping complex structures', status: 'planned'});
CREATE (:Repository {name: 'metagpt', url: 'https://github.com/geekan/MetaGPT', category: 'Agent Frameworks', purpose: 'Software company simulation with PM, Architect, and QA roles', status: 'active'});
CREATE (:Repository {name: 'awesome-chatgpt-prompts', url: 'https://github.com/f/awesome-chatgpt-prompts', category: 'Prompts Library', purpose: 'Curated library of roles and system prompt blueprints', status: 'active'});
CREATE (:Repository {name: 'prompt-engineering-guide', url: 'https://github.com/dair-ai/Prompt-Engineering-Guide', category: 'Prompts Library', purpose: 'Advanced guide on CoT, RAG prompts, and system constraints', status: 'active'});
CREATE (:Repository {name: 'promptfoo', url: 'https://github.com/promptfoo/promptfoo', category: 'Prompts Library', purpose: 'Prompt regression testing comparing accuracy, costs, and safety', status: 'active'});
CREATE (:Repository {name: 'modelcontextprotocol-servers', url: 'https://github.com/modelcontextprotocol/servers', category: 'MCP Ecosystem', purpose: 'Official MCP server implementations (Git, SQLite, Slack, Drive)', status: 'active'});
CREATE (:Repository {name: 'modelcontextprotocol-python-sdk', url: 'https://github.com/modelcontextprotocol/python-sdk', category: 'MCP Ecosystem', purpose: 'Python SDK for compiling custom MCP servers and resources', status: 'active'});
CREATE (:Repository {name: 'modelcontextprotocol-go-sdk', url: 'https://github.com/mark3labs/mcp-go', category: 'MCP Ecosystem', purpose: 'Go SDK for low-latency production MCP tool bindings', status: 'active'});
CREATE (:Repository {name: 'llamaindex', url: 'https://github.com/run-llama/llama_index', category: 'RAG & Graphs', purpose: 'Data connection framework linking vector indexes to agents', status: 'active'});
CREATE (:Repository {name: 'haystack', url: 'https://github.com/deepset-ai/haystack', category: 'RAG & Graphs', purpose: 'Enterprise level pipeline designer for search and Q&A systems', status: 'active'});
CREATE (:Repository {name: 'qdrant', url: 'https://github.com/qdrant/qdrant', category: 'RAG & Graphs', purpose: 'Production vector search engine tracking semantic embeddings', status: 'active'});
CREATE (:Repository {name: 'neo4j', url: 'https://github.com/neo4j/neo4j', category: 'RAG & Graphs', purpose: 'Graph database connecting repository capabilities and ventures', status: 'active'});
CREATE (:Repository {name: 'graphrag', url: 'https://github.com/microsoft/graphrag', category: 'RAG & Graphs', purpose: 'Extraction of entities and communities for structured summary RAG', status: 'active'});
CREATE (:Repository {name: 'activepieces', url: 'https://github.com/activepieces/activepieces', category: 'Automation', purpose: 'Self-hosted open source workflows alternative to Zapier', status: 'active'});
CREATE (:Repository {name: 'playwright', url: 'https://github.com/microsoft/playwright', category: 'Automation', purpose: 'Browser driver enabling clicks, logins, and form submissions', status: 'active'});
CREATE (:Repository {name: 'browser-use', url: 'https://github.com/browser-use/browser-use', category: 'Automation', purpose: 'Agentic browser automation overlay navigating pages natively', status: 'active'});
CREATE (:Repository {name: 'aider', url: 'https://github.com/Aider-AI/aider', category: 'Coding Agents', purpose: 'Terminal-based coding agent integrating direct file edits', status: 'active'});
CREATE (:Repository {name: 'continue', url: 'https://github.com/continuedev/continue', category: 'Coding Agents', purpose: 'IDE extensions linking models to code windows and chats', status: 'active'});
CREATE (:Repository {name: 'openhands', url: 'https://github.com/All-Hands-AI/OpenHands', category: 'Coding Agents', purpose: 'Fully autonomous coding workspace executor', status: 'active'});
CREATE (:Repository {name: 'deepeval', url: 'https://github.com/confident-ai/deepeval', category: 'AI Evaluation', purpose: 'Tests RAG recall, hallucination risks, and conversation quality', status: 'active'});
CREATE (:Repository {name: 'ragas', url: 'https://github.com/explodinggradients/ragas', category: 'AI Evaluation', purpose: 'Evaluation framework for retrieval augmented generation pipelines', status: 'active'});
CREATE (:Repository {name: 'openai-cookbook', url: 'https://github.com/openai/openai-cookbook', category: 'Cookbooks', purpose: 'OpenAI guidelines on function calling, agents, and fine-tunes', status: 'active'});
CREATE (:Repository {name: 'anthropic-cookbook', url: 'https://github.com/anthropics/anthropic-cookbook', category: 'Cookbooks', purpose: 'Anthropic workflows covering tool use, prompts, and caching', status: 'active'});
CREATE (:Repository {name: 'huggingface-cookbook', url: 'https://github.com/huggingface/cookbook', category: 'Cookbooks', purpose: 'Guides on running models, local fine-tunes, and transformers', status: 'active'});
CREATE (:Repository {name: 'vex-hero-site', url: 'file:///Users/acebless/Documents/vex-hero-site', category: 'Venture Frontends', purpose: 'Landing platform for VEX (Venture Execution) systems', status: 'active'});
CREATE (:Repository {name: 'classbuild', url: 'https://github.com/jtangen/classbuild', category: 'App Factory', purpose: 'AI-powered course generator built on evidence-based learning science', status: 'active'});
CREATE (:Repository {name: 'graphify', url: 'https://github.com/Worldwidebro/graphify', category: 'Code Intelligence', purpose: 'Repository graph generation', status: 'active'});
CREATE (:Repository {name: 'serena', url: 'https://github.com/Worldwidebro/serena', category: 'Code Intelligence', purpose: 'Semantic code understanding', status: 'active'});
CREATE (:Repository {name: 'sourcegraph-mcp', url: 'https://github.com/sourcegraph/mcp', category: 'MCP Ecosystem', purpose: 'Symbol search and code navigation', status: 'active'});
CREATE (:Repository {name: 'repomix', url: 'https://github.com/yamadashy/repomix', category: 'Code Intelligence', purpose: 'AI context packaging', status: 'active'});
CREATE (:Repository {name: 'understand-anything', url: 'https://github.com/Worldwidebro/understand-anything', category: 'Code Intelligence', purpose: 'Repository explanation and onboarding', status: 'active'});
CREATE (:Repository {name: 'litellm', url: 'https://github.com/BerriAI/litellm', category: 'Model Routing', purpose: 'Model routing and gateway management', status: 'active'});
CREATE (:Repository {name: 'ollama', url: 'https://github.com/ollama/ollama', category: 'Local AI Runtime', purpose: 'Local inference and embeddings', status: 'active'});
CREATE (:Repository {name: 'colibri', url: 'https://github.com/Worldwidebro/colibri', category: 'Local AI Runtime', purpose: 'High-performance local model inference', status: 'active'});
CREATE (:Repository {name: 'exo', url: 'https://github.com/exo-explore/exo', category: 'Local AI Runtime', purpose: 'Distributed inference across multiple devices', status: 'active'});
CREATE (:Repository {name: 'langfuse', url: 'https://github.com/langfuse/langfuse', category: 'AI Evaluation', purpose: 'Tracing, evaluation, and observability', status: 'active'});
CREATE (:Repository {name: 'postgresql', url: 'https://github.com/postgres/postgres', category: 'Data Layer', purpose: 'Operational database records', status: 'active'});
CREATE (:Repository {name: 'minio', url: 'https://github.com/minio/minio', category: 'Data Layer', purpose: 'Object storage management', status: 'active'});
CREATE (:Repository {name: 'stirling-pdf', url: 'https://github.com/Stirling-Tools/Stirling-PDF', category: 'Automation', purpose: 'Document conversion and preprocessing', status: 'active'});
CREATE (:Repository {name: 'public-apis', url: 'https://github.com/public-apis/public-apis', category: 'Automation', purpose: 'External service discovery', status: 'active'});
CREATE (:Repository {name: 'treemap', url: 'https://github.com/Worldwidebro/treemap', category: 'Infrastructure', purpose: 'Disk discovery and storage optimization', status: 'active'});
CREATE (:Repository {name: 'omnirouter', url: 'https://github.com/Worldwidebro/omnirouter', category: 'Model Routing', purpose: 'Dynamic LLM load-balancer / thinking router', status: 'active'});

// 2. Create Capability Nodes
CREATE (:Capability {id: 'unknown', name: 'unknown', category: '', description: ''});
CREATE (:Capability {id: 'local-model-gateway', name: 'Local AI Model Gateway', category: 'LOCAL AI', description: 'Gateways for accessing local models privately on offline machines.'});
CREATE (:Capability {id: 'private-api-layer', name: 'Private AI API Layer', category: 'LOCAL AI', description: 'OpenAI-compatible REST server wrapping local models.'});
CREATE (:Capability {id: 'hardware-acceleration', name: 'NPU/GPU Acceleration', category: 'LOCAL AI', description: 'Optimization hooks for Apple Silicon, NVIDIA CUDA, and AMD NPU hardware.'});
CREATE (:Capability {id: 'software-brain', name: 'Software Engineering Brain', category: 'CODE INTELLIGENCE', description: 'Semantic codebase graphing, impact assessment, and change tracking.'});
CREATE (:Capability {id: 'repo-scanner', name: 'Code Dependency Scanner', category: 'CODE INTELLIGENCE', description: 'Zero-server dependency tree scanner mapping repository relations.'});
CREATE (:Capability {id: 'personal-ceo', name: 'Personal AI CEO Layer', category: 'AI EMPLOYEES', description: 'Top-level coordination, calendar sync, strategy, and personal assistance.'});
CREATE (:Capability {id: 'cowork-desktop', name: 'Cowork Desktop Workspace', category: 'AI EMPLOYEES', description: 'Local GUI container environment for cooperative AI agent workers.'});
CREATE (:Capability {id: 'mvp-app-factory', name: 'Rapid MVP App Factory', category: 'APP FACTORY', description: 'Generates database-backed applications from standard text descriptions.'});
CREATE (:Capability {id: 'process-orchestrator', name: 'BPMN Process Orchestrator', category: 'AUTOMATION', description: 'Formally maps and drives multi-step approvals and integrations.'});
CREATE (:Capability {id: 'aws-simulation', name: 'Local AWS Cloud Simulator', category: 'INFRASTRUCTURE', description: 'Emulates AWS endpoints (Lambda, S3, DynamoDB) locally for cost-free'});
CREATE (:Capability {id: 'pen-tester', name: 'Penetration Testing Agent', category: 'SECURITY', description: 'Autonomous scanning of open ports and credentials verification.'});
CREATE (:Capability {id: 'second-brain-sync', name: 'Second Brain Sync', category: 'DATA MEMORY', description: 'Synchronizes personal notes, wikis, and markdown documents into agent'});
CREATE (:Capability {id: 'meeting-transcriber', name: 'Meeting Transcription & Summary', category: 'VOICE', description: 'Audio diarization, speaker detection, and action item summary generation.'});
CREATE (:Capability {id: 'cctv-vision', name: 'CCTV Object Detection', category: 'COMPUTER VISION', description: 'Parses video streams for people, objects, and activities locally.'});
CREATE (:Capability {id: 'landing-frontends', name: 'Venture Presentation Frontends', category: 'VENTURE FRONTENDS', description: 'Static and dynamic web landing layouts for launching ventures.'});
CREATE (:Capability {id: 'course-generator', name: 'AI Course Generator', category: 'APP FACTORY', description: 'Generates complete multimedia-ready courses, slide decks, and quiz'});
CREATE (:Capability {id: 'stealth-browsing', name: 'Stealth Agentic Browsing', category: 'COMPUTER VISION', description: 'Playwright/stealth spoofed browser execution for automated data extraction.'});
CREATE (:Capability {id: 'agent-sandbox-isolation', name: 'Secure Agent Sandbox', category: 'SECURITY', description: 'Filesystem and network command isolation sandbox for AI agents.'});
CREATE (:Capability {id: 'real-time-cost-tracking', name: 'Real-Time Token Cost Tracking', category: 'INFRASTRUCTURE', description: 'OpenTelemetry cost logging and budget limits for multi-agent execution.'});
CREATE (:Capability {id: 'agent-consensus-memory', name: 'Consensus-Based Agent Memory', category: 'DATA MEMORY', description: 'Byzantine Fault Tolerant shared memory systems for collaborative agent'});
CREATE (:Capability {id: 'repository-graphing', name: 'Repository Graphing', category: 'CODE INTELLIGENCE', description: 'Repository graph generation and visual dependency mappings.'});
CREATE (:Capability {id: 'semantic-understanding', name: 'Semantic Understanding', category: 'CODE INTELLIGENCE', description: 'Semantic code understanding, explanation, and developer onboarding.'});
CREATE (:Capability {id: 'distributed-inference', name: 'Distributed Inference', category: 'LOCAL AI', description: 'Distributed inference across multiple devices locally.'});
CREATE (:Capability {id: 'document-preprocessing', name: 'Document Preprocessing', category: 'AUTOMATION', description: 'Document conversion, Stirling PDF preprocessing, and metadata extraction.'});
CREATE (:Capability {id: 'storage-optimization', name: 'Storage Optimization', category: 'INFRASTRUCTURE', description: 'Disk discovery, duplicate tracking, and storage optimization.'});
CREATE (:Capability {id: 'thinking-routing', name: 'Dynamic LLM Routing', category: 'LOCAL AI', description: 'Dynamic LLM load-balancer and thinking budget routing engine.'});

// 3. Create Agent Nodes
CREATE (:Agent {name: 'DevOps Agent'});
CREATE (:Agent {name: 'Backend Engineer Agent'});
CREATE (:Agent {name: 'Project Manager Agent'});
CREATE (:Agent {name: 'Compliance Agent'});
CREATE (:Agent {name: 'Frontend Engineer Agent'});
CREATE (:Agent {name: 'Research Agent'});
CREATE (:Agent {name: 'Opus Prime'});
CREATE (:Agent {name: 'AI Architect Agent'});
CREATE (:Agent {name: 'CTO Agent'});
CREATE (:Agent {name: 'Quinn Ops'});
CREATE (:Agent {name: 'Claude Architect'});
CREATE (:Agent {name: 'Mary Analyst'});
CREATE (:Agent {name: 'CEO Agent'});
CREATE (:Agent {name: 'Venture Creator Agent'});
CREATE (:Agent {name: 'COO Agent'});

// 4. Create Graph Relationships
MATCH (r:Repository {name: ''}), (c:Capability {id: ''}) CREATE (r)-[:PROVIDES]->(c);
MATCH (r:Repository {name: 'gpt4all'}), (c:Capability {id: 'local-model-gateway'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'local-model-gateway'}), (a:Agent {name: 'AI Architect Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'localai'}), (c:Capability {id: 'private-api-layer'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'private-api-layer'}), (a:Agent {name: 'Backend Engineer Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'gitnexus'}), (c:Capability {id: 'repo-scanner'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'repo-scanner'}), (a:Agent {name: 'CTO Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'openhuman'}), (c:Capability {id: 'personal-ceo'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'personal-ceo'}), (a:Agent {name: 'CEO Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'dyad'}), (c:Capability {id: 'mvp-app-factory'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'mvp-app-factory'}), (a:Agent {name: 'Venture Creator Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'camunda'}), (c:Capability {id: 'process-orchestrator'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'process-orchestrator'}), (a:Agent {name: 'COO Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'localstack'}), (c:Capability {id: 'aws-simulation'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'aws-simulation'}), (a:Agent {name: 'DevOps Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'metatron'}), (c:Capability {id: 'pen-tester'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'pen-tester'}), (a:Agent {name: 'Compliance Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'obsidian-second-brain'}), (c:Capability {id: 'second-brain-sync'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'second-brain-sync'}), (a:Agent {name: 'CEO Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'meetily'}), (c:Capability {id: 'meeting-transcriber'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'meeting-transcriber'}), (a:Agent {name: 'Project Manager Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'vex-hero-site'}), (c:Capability {id: 'landing-frontends'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'landing-frontends'}), (a:Agent {name: 'Frontend Engineer Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'PaddleOCR'}), (c:Capability {id: 'document-extraction'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'document-extraction'}), (a:Agent {name: 'Research Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'Qdrant'}), (c:Capability {id: 'vector-search'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'vector-search'}), (a:Agent {name: 'Research Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'LlamaIndex'}), (c:Capability {id: 'rag-orchestrator'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'rag-orchestrator'}), (a:Agent {name: 'Research Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'classbuild'}), (c:Capability {id: 'course-generator'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'course-generator'}), (a:Agent {name: 'Venture Creator Agent'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'graphify'}), (c:Capability {id: 'repository-graphing'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'repository-graphing'}), (a:Agent {name: 'Claude Architect'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'serena'}), (c:Capability {id: 'semantic-understanding'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'semantic-understanding'}), (a:Agent {name: 'Mary Analyst'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'understand-anything'}), (c:Capability {id: 'semantic-understanding'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'semantic-understanding'}), (a:Agent {name: 'Claude Architect'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'exo'}), (c:Capability {id: 'distributed-inference'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'distributed-inference'}), (a:Agent {name: 'Quinn Ops'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'stirling-pdf'}), (c:Capability {id: 'document-preprocessing'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'document-preprocessing'}), (a:Agent {name: 'Opus Prime'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'treemap'}), (c:Capability {id: 'storage-optimization'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'storage-optimization'}), (a:Agent {name: 'Quinn Ops'}) CREATE (a)-[:USES]->(c);
MATCH (r:Repository {name: 'omnirouter'}), (c:Capability {id: 'thinking-routing'}) CREATE (r)-[:PROVIDES]->(c);
MATCH (c:Capability {id: 'thinking-routing'}), (a:Agent {name: 'Claude Architect'}) CREATE (a)-[:USES]->(c);