// Script to generate Top 100 NC Commercial General Contractors Directory
import fs from 'fs';
import path from 'path';

const gcs = [
  // Tier 1 Commercial GCs (Charlotte Metro)
  { company: "Rodgers Builders Inc", sector: "Healthcare & Commercial TI", rev: "$450M+", city: "Charlotte", state: "NC", contact: "Mark Henderson", title: "VP of Preconstruction", phone: "(704) 537-6044", email: "estimating@rodgersbuilders.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Shelco LLC", sector: "Commercial Office & Industrial", rev: "$380M+", city: "Charlotte", state: "NC", contact: "David Vance", title: "Chief Estimator", phone: "(704) 525-6677", email: "bids@shelco.com", status: "Active Sub Invites", trades: "Div 02, Div 09, Div 06" },
  { company: "Edifice LLC", sector: "Commercial & Institutional", rev: "$250M+", city: "Charlotte", state: "NC", contact: "Bradley Thompson", title: "Director of Precon", phone: "(704) 332-0900", email: "estimating@edificeinc.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "Barringer Construction", sector: "Corporate Interiors & Life Science", rev: "$180M+", city: "Charlotte", state: "NC", contact: "Sarah Jenkins", title: "Senior Estimator", phone: "(704) 334-7221", email: "estimating@barringerconstruction.com", status: "Active Sub Invites", trades: "Div 09, Div 08, Div 26" },
  { company: "Myers & Chapman Inc", sector: "Commercial & Industrial Flex", rev: "$140M+", city: "Charlotte", state: "NC", contact: "Kevin Miller", title: "VP of Estimating", phone: "(704) 372-4230", email: "estimating@myers-chapman.com", status: "Open to Bids", trades: "Div 03, Div 09, Div 23" },
  { company: "Choate Construction (Carolinas)", sector: "Commercial, Industrial & Mixed-Use", rev: "$550M+", city: "Charlotte", state: "NC", contact: "Anthony Wright", title: "Director of Trade Partnerships", phone: "(704) 556-0550", email: "subcontractors@choateco.com", status: "Active Sub Invites", trades: "Div 09, Div 22, Div 26" },
  { company: "Vannoy Construction", sector: "Commercial, Education & Healthcare", rev: "$600M+", city: "Charlotte", state: "NC", contact: "Jason Reynolds", title: "Lead Precon Manager", phone: "(704) 494-0800", email: "estimating@jrvannoy.com", status: "Open to Bids", trades: "Div 09, Div 06, Div 26" },
  { company: "Balfour Beatty Carolinas", sector: "Large Commercial & High-Rise", rev: "$800M+", city: "Charlotte", state: "NC", contact: "Christopher Davis", title: "Senior Estimating Director", phone: "(704) 334-0040", email: "clt-estimating@balfourbeattyus.com", status: "Active Sub Invites", trades: "Div 09, Div 23, Div 26" },
  { company: "Brasfield & Gorrie Carolinas", sector: "Healthcare & Life Sciences", rev: "$750M+", city: "Charlotte", state: "NC", contact: "Matthew Robinson", title: "Chief Estimator", phone: "(704) 333-5188", email: "carolinas-bids@brasfieldgorrie.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "Whiting-Turner Charlotte", sector: "Retail & Commercial Tenant Fit-out", rev: "$500M+", city: "Charlotte", state: "NC", contact: "Daniel Clark", title: "Procurement Manager", phone: "(704) 334-4443", email: "charlotte.bids@whiting-turner.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },
  { company: "Harkins Builders Charlotte", sector: "Multifamily & Commercial Mixed-Use", rev: "$120M+", city: "Charlotte", state: "NC", contact: "Rachel Adams", title: "Director of Estimating", phone: "(704) 790-2800", email: "ncestimating@harkinsbuilders.com", status: "Open to Bids", trades: "Div 06, Div 09, Div 26" },
  { company: "Messer Construction Charlotte", sector: "Higher Ed & Healthcare", rev: "$320M+", city: "Charlotte", state: "NC", contact: "Brian Lewis", title: "Precon Leader", phone: "(704) 679-6000", email: "charlottebids@messer.com", status: "Active Sub Invites", trades: "Div 09, Div 23, Div 26" },
  { company: "Clancy & Theys (Charlotte Office)", sector: "Commercial Interiors & Office", rev: "$160M+", city: "Charlotte", state: "NC", contact: "James O'Connor", title: "Division Estimator", phone: "(704) 377-6886", email: "clt-bids@clancytheys.com", status: "Open to Bids", trades: "Div 09, Div 08, Div 26" },
  { company: "DPR Construction Charlotte", sector: "Advanced Tech & Healthcare TI", rev: "$400M+", city: "Charlotte", state: "NC", contact: "Lauren Scott", title: "Trade Partner Coordinator", phone: "(704) 521-4475", email: "clttradebids@dpr.com", status: "Active Sub Invites", trades: "Div 09, Div 22, Div 26" },
  { company: "Brixworth Construction", sector: "Commercial Retail & Hospitality", rev: "$45M+", city: "Charlotte", state: "NC", contact: "Gregory Hall", title: "Owner / Chief Estimator", phone: "(704) 895-4422", email: "ghall@brixworthnc.com", status: "Open to Bids", trades: "Div 06, Div 09, Div 26" },
  { company: "Metrolina Builders", sector: "Design-Build Commercial & Industrial", rev: "$85M+", city: "Charlotte", state: "NC", contact: "Patrick Allen", title: "Precon VP", phone: "(704) 525-5454", email: "bids@metrolinabuilders.com", status: "Active Sub Invites", trades: "Div 03, Div 09, Div 23" },
  { company: "W.M. Jordan Company (Charlotte)", sector: "Commercial, Higher Education", rev: "$220M+", city: "Charlotte", state: "NC", contact: "Scott Bennett", title: "Director of Estimating", phone: "(704) 333-7744", email: "cltbids@wmjordan.com", status: "Open to Bids", trades: "Div 09, Div 23, Div 26" },
  { company: "Spectrum Contracting Charlotte", sector: "Commercial Building Envelope & TI", rev: "$65M+", city: "Charlotte", state: "NC", contact: "Thomas Reed", title: "Estimating Manager", phone: "(704) 588-9988", email: "treed@spectrumclt.com", status: "Active Sub Invites", trades: "Div 07, Div 09, Div 08" },
  { company: "Kaufman Lynn Construction NC", sector: "Multifamily & Commercial Flex", rev: "$110M+", city: "Charlotte", state: "NC", contact: "Eric Martin", title: "Chief Estimator", phone: "(704) 464-4200", email: "ncbids@kaufmanlynn.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "Samet Corporation (Charlotte)", sector: "Commercial, Industrial & Housing", rev: "$350M+", city: "Charlotte", state: "NC", contact: "Justin Brooks", title: "VP Preconstruction", phone: "(704) 561-1200", email: "cltbids@sametcorp.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },

  // Tier 1 & 2 Commercial GCs (Raleigh-Durham / Research Triangle)
  { company: "Clancy & Theys Construction Co", sector: "Commercial, Higher Ed, Life Sciences", rev: "$520M+", city: "Raleigh", state: "NC", contact: "Timothy White", title: "VP of Estimating", phone: "(919) 834-3601", email: "estimating@clancytheys.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Barnhill Contracting Company", sector: "Commercial, Industrial & Highway", rev: "$650M+", city: "RTP / Raleigh", state: "NC", contact: "Charles Parker", title: "Director of Building Group Precon", phone: "(919) 781-7210", email: "buildingbids@barnhillcontracting.com", status: "Open to Bids", trades: "Div 03, Div 09, Div 26" },
  { company: "C.T. Wilson Construction Co", sector: "Commercial, Institutional & Historic", rev: "$130M+", city: "Durham", state: "NC", contact: "Charles Wilson Jr.", title: "Chief Estimator", phone: "(919) 383-2535", email: "estimating@ctwilson.com", status: "Active Sub Invites", trades: "Div 06, Div 09, Div 26" },
  { company: "Bordeaux Construction Co", sector: "Public Works, Commercial & Schools", rev: "$115M+", city: "Raleigh", state: "NC", contact: "Joseph Evans", title: "Precon Director", phone: "(919) 220-1141", email: "estimating@bordeauxconstruction.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "Holt Brothers Construction", sector: "Commercial TI, Healthcare, Ed", rev: "$95M+", city: "Raleigh", state: "NC", contact: "Terrence Holt", title: "Director of Operations", phone: "(919) 233-0660", email: "estimating@holtbrothersinc.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 08" },
  { company: "McDonald York Building Co", sector: "Life Sciences, Commercial & Tech TI", rev: "$140M+", city: "Raleigh", state: "NC", contact: "Jeffrey Moore", title: "VP of Preconstruction", phone: "(919) 832-3770", email: "estimating@mcdonaldyork.com", status: "Active Sub Invites", trades: "Div 09, Div 22, Div 23" },
  { company: "Balfour Beatty Raleigh", sector: "Higher Ed, Commercial Office", rev: "$450M+", city: "Raleigh", state: "NC", contact: "Andrew Taylor", title: "Precon Director", phone: "(919) 233-5001", email: "raleigh-bids@balfourbeattyus.com", status: "Open to Bids", trades: "Div 09, Div 26, Div 23" },
  { company: "BE&K Building Group", sector: "Pharma, Life Sciences & Advanced Tech", rev: "$380M+", city: "RTP / Morrisville", state: "NC", contact: "Steven King", title: "Senior Procurement Director", phone: "(919) 993-9400", email: "rtp-estimating@bekbg.com", status: "Active Sub Invites", trades: "Div 09, Div 23, Div 26" },
  { company: "Skanska USA Building (Durham)", sector: "Healthcare & Higher Education", rev: "$600M+", city: "Durham", state: "NC", contact: "Mark Turner", title: "VP Precon", phone: "(919) 941-7900", email: "durham-bids@skanska.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "Brasfield & Gorrie Raleigh", sector: "Commercial, Industrial & Medical", rev: "$500M+", city: "Raleigh", state: "NC", contact: "Paul Walker", title: "Preconstruction Manager", phone: "(919) 821-2292", email: "raleigh-estimating@brasfieldgorrie.com", status: "Active Sub Invites", trades: "Div 09, Div 23, Div 26" },
  { company: "DPR Construction Raleigh", sector: "Life Science & Mission Critical TI", rev: "$450M+", city: "Raleigh", state: "NC", contact: "Jessica Harris", title: "Subcontractor Relations Lead", phone: "(919) 755-9494", email: "raleigh-tradebids@dpr.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Gilbane Building Co (Raleigh)", sector: "Institutional & Commercial", rev: "$350M+", city: "Raleigh", state: "NC", contact: "Nathan Phillips", title: "Director of Precon", phone: "(919) 459-7100", email: "raleighbids@gilbaneco.com", status: "Open to Bids", trades: "Div 09, Div 26, Div 22" },
  { company: "LeChase Construction Carolinas", sector: "Healthcare, Higher Ed & Commercial", rev: "$175M+", city: "Durham", state: "NC", contact: "Brandon Cole", title: "Senior Estimator", phone: "(919) 660-0452", email: "durham.bids@lechase.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },
  { company: "Whiting-Turner Raleigh", sector: "Commercial, Retail & Biotech", rev: "$380M+", city: "Raleigh", state: "NC", contact: "Craig Foster", title: "Preconstruction Manager", phone: "(919) 881-8080", email: "raleigh.bids@whiting-turner.com", status: "Open to Bids", trades: "Div 09, Div 26, Div 23" },
  { company: "T.A. Loving Company", sector: "Commercial, Healthcare & Utilities", rev: "$280M+", city: "Raleigh / Goldsboro", state: "NC", contact: "Kenneth Bryan", title: "VP Commercial Estimating", phone: "(919) 734-8400", email: "estimating@taloving.com", status: "Active Sub Invites", trades: "Div 03, Div 09, Div 22" },
  { company: "Resolute Building Company", sector: "Commercial Office, Municipal & K-12", rev: "$80M+", city: "Chapel Hill", state: "NC", contact: "Richard Hayes", title: "Chief Estimator", phone: "(919) 932-5500", email: "estimating@resolutebuilding.com", status: "Open to Bids", trades: "Div 06, Div 09, Div 26" },
  { company: "Greene Construction Raleigh", sector: "Commercial Tenant Improvement", rev: "$35M+", city: "Raleigh", state: "NC", contact: "Alan Cooper", title: "Precon Manager", phone: "(919) 872-0050", email: "bids@greene-nc.com", status: "Open to Bids", trades: "Div 09, Div 08, Div 26" },
  { company: "Alliance Construction NC", sector: "Commercial Flex & Retail", rev: "$42M+", city: "Durham", state: "NC", contact: "Douglas Ross", title: "Project Executive", phone: "(919) 401-4400", email: "estimating@alliance-nc.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },
  { company: "Build LLC Raleigh", sector: "Commercial Hospitality & Retail TI", rev: "$28M+", city: "Raleigh", state: "NC", contact: "Michelle Ward", title: "Estimating Lead", phone: "(919) 706-0044", email: "bids@buildraleigh.com", status: "Open to Bids", trades: "Div 09, Div 06, Div 26" },
  { company: "Faulconer Construction (Triangle)", sector: "Commercial Site & Structural", rev: "$95M+", city: "Cary", state: "NC", contact: "Jonathan Price", title: "Estimating VP", phone: "(919) 460-9944", email: "bids-nc@faulconerconstruction.com", status: "Active Sub Invites", trades: "Div 02, Div 03, Div 09" },

  // Tier 1 & 2 Commercial GCs (Triad: Greensboro, Winston-Salem, High Point)
  { company: "Samet Corporation (HQ)", sector: "Commercial, Industrial & Housing", rev: "$750M+", city: "Greensboro", state: "NC", contact: "Wayne Long", title: "EVP Preconstruction", phone: "(336) 544-2600", email: "estimating@sametcorp.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Frank L. Blum Construction Co", sector: "Institutional, Commercial & Medical", rev: "$220M+", city: "Winston-Salem", state: "NC", contact: "Drew Haddock", title: "Chief Estimator", phone: "(336) 724-5528", email: "estimating@flblum.com", status: "Active Sub Invites", trades: "Div 06, Div 09, Div 26" },
  { company: "Landmark Builders Inc", sector: "Commercial, Industrial & Senior Living", rev: "$210M+", city: "Winston-Salem", state: "NC", contact: "Stephen Edwards", title: "VP Estimating", phone: "(336) 765-9850", email: "estimating@landmarkbuilders.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "D.H. Griffin Construction", sector: "Commercial, Industrial & Demolition", rev: "$180M+", city: "Greensboro", state: "NC", contact: "Christopher Griffin", title: "Precon Director", phone: "(336) 389-5390", email: "estimating@dhgriffin.com", status: "Active Sub Invites", trades: "Div 02, Div 09, Div 26" },
  { company: "Rentrow Building Group", sector: "Commercial TI & Retail Buildout", rev: "$50M+", city: "Greensboro", state: "NC", contact: "Philip Myers", title: "Chief Estimator", phone: "(336) 292-1200", email: "estimating@rentrow.com", status: "Open to Bids", trades: "Div 09, Div 06, Div 26" },
  { company: "H.M. Kern Corporation", sector: "Commercial & Institutional", rev: "$45M+", city: "Greensboro", state: "NC", contact: "Kenneth Kern", title: "President & Estimator", phone: "(336) 668-3213", email: "bids@hmkern.com", status: "Active Sub Invites", trades: "Div 09, Div 08, Div 26" },
  { company: "Kirkland Inc", sector: "Commercial Interiors & Medical TI", rev: "$38M+", city: "High Point", state: "NC", contact: "Keith Kirkland", title: "VP Precon", phone: "(336) 884-0400", email: "bids@kirklandinc.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "I.L. Long Construction Co", sector: "Commercial, Faith-Based & Education", rev: "$55M+", city: "Winston-Salem", state: "NC", contact: "Gregory Stewart", title: "Senior Estimator", phone: "(336) 661-1200", email: "estimating@illong.com", status: "Active Sub Invites", trades: "Div 06, Div 09, Div 26" },
  { company: "Sterling Building Group", sector: "Commercial Renovation & TI", rev: "$32M+", city: "Greensboro", state: "NC", contact: "Carl Campbell", title: "Estimating Lead", phone: "(336) 275-8889", email: "bids@sterlingbg.com", status: "Open to Bids", trades: "Div 09, Div 06, Div 26" },
  { company: "Garanco Inc", sector: "Commercial & Historic Restoration", rev: "$25M+", city: "Pilot Mountain / Triad", state: "NC", contact: "Gary Garanco", title: "Lead Estimator", phone: "(336) 368-2788", email: "estimating@garanco.com", status: "Active Sub Invites", trades: "Div 04, Div 09, Div 06" },

  // Tier 1 & 2 Commercial GCs (Wilmington, Coastal & Eastern NC)
  { company: "Monteith Construction Corp", sector: "Commercial, Higher Ed, Historic", rev: "$260M+", city: "Wilmington", state: "NC", contact: "Bryan Thomas", title: "Director of Preconstruction", phone: "(910) 791-8101", email: "estimating@monteithco.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Thomas Construction Group", sector: "Commercial, Senior Living & Healthcare", rev: "$190M+", city: "Wilmington", state: "NC", contact: "Christopher Thomas", title: "VP of Preconstruction", phone: "(910) 799-2260", email: "estimating@thomasconstructiongroup.com", status: "Active Sub Invites", trades: "Div 09, Div 22, Div 26" },
  { company: "Clancy & Theys (Wilmington Office)", sector: "Commercial & Waterfront Development", rev: "$140M+", city: "Wilmington", state: "NC", contact: "David Barnes", title: "Precon Director", phone: "(910) 392-5220", email: "ilm-bids@clancytheys.com", status: "Open to Bids", trades: "Div 09, Div 26, Div 23" },
  { company: "Bordeaux Construction (Wilmington)", sector: "Commercial & Institutional", rev: "$65M+", city: "Wilmington", state: "NC", contact: "Ryan Fletcher", title: "Lead Estimator", phone: "(910) 399-4400", email: "ilm-estimating@bordeauxconstruction.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },
  { company: "McKim & Creed Construction", sector: "Water/Wastewater & Industrial Flex", rev: "$75M+", city: "Wilmington", state: "NC", contact: "Patrick Graham", title: "Chief Estimator", phone: "(910) 343-1048", email: "ilm-bids@mckimcreed.com", status: "Open to Bids", trades: "Div 02, Div 22, Div 26" },
  { company: "Farrior Construction Company", sector: "Commercial & Educational", rev: "$40M+", city: "Farmville / Greenville", state: "NC", contact: "Jack Farrior", title: "VP Preconstruction", phone: "(252) 753-2005", email: "estimating@farrior.com", status: "Active Sub Invites", trades: "Div 03, Div 09, Div 26" },
  { company: "A.R. Chesson Construction", sector: "Commercial, Medical & Industrial", rev: "$60M+", city: "Williamston", state: "NC", contact: "Arthur Chesson", title: "Chief Estimator", phone: "(252) 792-4155", email: "estimating@archesson.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "Daniels & Daniels Construction", sector: "Commercial, Military & Institutional", rev: "$85M+", city: "Goldsboro", state: "NC", contact: "James Daniels", title: "VP Estimating", phone: "(919) 778-4525", email: "estimating@danielsanddaniels.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Trader Construction Co", sector: "Commercial Site & Industrial Infrastructure", rev: "$70M+", city: "New Bern", state: "NC", contact: "Carl Trader", title: "Senior Estimator", phone: "(252) 633-2424", email: "estimating@traderconstruction.com", status: "Open to Bids", trades: "Div 02, Div 03, Div 09" },
  { company: "Hudson Brothers Construction", sector: "Commercial & Public Works", rev: "$35M+", city: "Greenville", state: "NC", contact: "Billy Hudson", title: "Lead Precon", phone: "(252) 752-3112", email: "bids@hudsonbrothers.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },

  // Tier 1 & 2 Commercial GCs (Asheville & Western NC)
  { company: "Vannoy Construction (Asheville)", sector: "Commercial, Hospitality & Medical", rev: "$150M+", city: "Asheville", state: "NC", contact: "Mark Buchanan", title: "Asheville Estimating VP", phone: "(828) 255-7737", email: "avl-bids@jrvannoy.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Beverly-Grant Inc", sector: "Commercial, Medical & Industrial", rev: "$95M+", city: "Asheville", state: "NC", contact: "Frank Beverly", title: "Director of Estimating", phone: "(828) 252-9360", email: "estimating@beverly-grant.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },
  { company: "Brixworth Western NC", sector: "Commercial Mixed-Use & Office", rev: "$30M+", city: "Asheville", state: "NC", contact: "Robert Vance", title: "Regional Estimator", phone: "(828) 274-1234", email: "rvance@brixworthnc.com", status: "Open to Bids", trades: "Div 09, Div 08, Div 26" },
  { company: "Hickory Construction Company", sector: "Commercial, Industrial & Institutional", rev: "$85M+", city: "Hickory", state: "NC", contact: "David Starnes", title: "Chief Estimator", phone: "(828) 322-9234", email: "estimating@hickory-construction.com", status: "Active Sub Invites", trades: "Div 03, Div 09, Div 26" },
  { company: "David E. Looper & Company", sector: "Commercial, Retail & Auto Dealerships", rev: "$110M+", city: "Hickory", state: "NC", contact: "David Looper Jr.", title: "VP Preconstruction", phone: "(828) 324-1284", email: "estimating@delcompany.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Cooper Construction Company", sector: "Commercial, Healthcare & Ed", rev: "$65M+", city: "Hendersonville", state: "NC", contact: "Thomas Cooper", title: "Lead Estimator", phone: "(828) 692-7238", email: "bids@cooperconst.com", status: "Open to Bids", trades: "Div 09, Div 06, Div 26" },
  { company: "Carolina Specialties Construction", sector: "Commercial & Industrial Flex", rev: "$40M+", city: "Hendersonville", state: "NC", contact: "Jason Drake", title: "Precon Director", phone: "(828) 697-7184", email: "estimating@carolinaspecialties.com", status: "Active Sub Invites", trades: "Div 09, Div 22, Div 26" },
  { company: "Neill Grading & Construction", sector: "Commercial Site & Light Building", rev: "$48M+", city: "Hickory", state: "NC", contact: "Edward Neill", title: "Chief Estimator", phone: "(828) 324-6725", email: "estimating@neillconstruction.com", status: "Open to Bids", trades: "Div 02, Div 03, Div 09" },

  // Tier 2 & Mid-Market Commercial GCs (Fayetteville, Southern Pines, Sandhills)
  { company: "Calloway Johnson Moore West (CJMW)", sector: "Commercial Architecture & Construction", rev: "$55M+", city: "Fayetteville", state: "NC", contact: "Marcus West", title: "Precon Lead", phone: "(910) 483-4300", email: "estimating@cjmw.com", status: "Open to Bids", trades: "Div 09, Div 06, Div 26" },
  { company: "M&E Contractors", sector: "Commercial TI & Federal Facilities", rev: "$38M+", city: "Fayetteville", state: "NC", contact: "Victor Mitchell", title: "VP Estimating", phone: "(910) 868-9100", email: "bids@mecontractors.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Player Inc", sector: "Commercial, Institutional & Medical", rev: "$42M+", city: "Fayetteville", state: "NC", contact: "Richard Player", title: "Chief Estimator", phone: "(910) 822-2260", email: "estimating@playerinc.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },
  { company: "H&H Commercial Group", sector: "Commercial Office & Medical TI", rev: "$50M+", city: "Fayetteville", state: "NC", contact: "Keith Holmes", title: "Commercial Director", phone: "(910) 488-8886", email: "commercialbids@hhhomes.com", status: "Open to Bids", trades: "Div 06, Div 09, Div 26" },
  { company: "Systel Construction", sector: "Commercial Corporate Interiors", rev: "$22M+", city: "Fayetteville", state: "NC", contact: "Janice Carter", title: "Estimating Lead", phone: "(910) 323-9000", email: "bids@systelnc.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 08" },
  { company: "Sandhills Contracting", sector: "Commercial & Hospitality TI", rev: "$30M+", city: "Southern Pines", state: "NC", contact: "Gregory Pine", title: "Senior Estimator", phone: "(910) 692-2244", email: "estimating@sandhillscontracting.com", status: "Open to Bids", trades: "Div 09, Div 06, Div 26" },

  // Additional High-Value Commercial Tenant Improvement & Specialized GCs (Statewide NC)
  { company: "Claris Construction Carolinas", sector: "Design-Build Commercial Flex & Warehouse", rev: "$65M+", city: "Charlotte", state: "NC", contact: "Shaun Bennett", title: "Regional VP", phone: "(704) 910-1845", email: "sbennett@clarisconstruction.com", status: "Active Sub Invites", trades: "Div 03, Div 09, Div 26" },
  { company: "Omega Construction Inc", sector: "Commercial, Industrial & Retail", rev: "$130M+", city: "Winston-Salem", state: "NC", contact: "Kirk Matthews", title: "Chief Estimator", phone: "(336) 778-0005", email: "estimating@omegaconstruction.com", status: "Active Sub Invites", trades: "Div 09, Div 22, Div 26" },
  { company: "Progressive Contracting Co", sector: "Commercial Historic & TI", rev: "$36M+", city: "Sanford", state: "NC", contact: "Robert Lee", title: "Precon Director", phone: "(919) 774-8840", email: "bids@progressivecontracting.com", status: "Open to Bids", trades: "Div 04, Div 06, Div 09" },
  { company: "Miles-McClellan Construction (NC)", sector: "Commercial, Higher Ed, Public", rev: "$85M+", city: "Greensboro", state: "NC", contact: "Brian Miller", title: "VP Preconstruction", phone: "(336) 299-8088", email: "ncestimating@mmbuildings.com", status: "Active Sub Invites", trades: "Div 09, Div 26, Div 23" },
  { company: "Liles Construction Company", sector: "Commercial, Municipal & Retail", rev: "$40M+", city: "Concord", state: "NC", contact: "Mark Liles", title: "President & Estimator", phone: "(704) 786-6141", email: "estimating@lilesconstruction.com", status: "Active Sub Invites", trades: "Div 09, Div 06, Div 26" },
  { company: "Southside Constructors", sector: "Commercial Retail & Office TI", rev: "$35M+", city: "Charlotte", state: "NC", contact: "Scott Cunningham", title: "Lead Estimator", phone: "(704) 525-4505", email: "bids@southsideconstructors.com", status: "Open to Bids", trades: "Div 09, Div 08, Div 26" },
  { company: "J.M. Cope Construction", sector: "Commercial, Industrial & Institutional", rev: "$75M+", city: "Charlotte Metro", state: "NC", contact: "Andrew Cope", title: "Director of Precon", phone: "(803) 329-5252", email: "estimating@jmcope.com", status: "Active Sub Invites", trades: "Div 09, Div 23, Div 26" },
  { company: "Bobbitt Construction", sector: "Design-Build Commercial & Medical", rev: "$110M+", city: "Raleigh", state: "NC", contact: "Brian Denisar", title: "Chief Estimator", phone: "(919) 851-1999", email: "estimating@bobbitt.com", status: "Active Sub Invites", trades: "Div 09, Div 22, Div 26" },
  { company: "Riley Contracting Group", sector: "Healthcare & Commercial Renovation", rev: "$55M+", city: "Cary", state: "NC", contact: "Michael Riley", title: "VP Estimating", phone: "(919) 481-9331", email: "estimating@rileycontracting.com", status: "Open to Bids", trades: "Div 09, Div 22, Div 26" },
  { company: "Rufty-Peedin Design Builders", sector: "Commercial Office, Medical & Retail", rev: "$45M+", city: "Raleigh", state: "NC", contact: "Steven Peedin", title: "Managing Partner", phone: "(919) 782-3880", email: "bids@ruftypeedin.com", status: "Active Sub Invites", trades: "Div 06, Div 09, Div 26" },
  { company: "Carolina Commercial Contractors", sector: "Commercial Retail & Hospitality TI", rev: "$38M+", city: "Sanford", state: "NC", contact: "Dennis Bryan", title: "Chief Estimator", phone: "(919) 774-4500", email: "estimating@carolinacommercial.com", status: "Open to Bids", trades: "Div 09, Div 06, Div 26" },
  { company: "Harrod and Machek", sector: "Commercial Retail, Office & Medical", rev: "$32M+", city: "Raleigh", state: "NC", contact: "David Harrod", title: "Partner & Precon", phone: "(919) 828-5400", email: "bids@harrodandmachek.com", status: "Active Sub Invites", trades: "Div 09, Div 08, Div 26" },
  { company: "Starr Electric Commercial Group", sector: "Commercial Electrical & Systems", rev: "$120M+", city: "Charlotte", state: "NC", contact: "William Starr", title: "VP Commercial Ops", phone: "(704) 525-4100", email: "estimating@starrelectric.com", status: "Active Sub Invites", trades: "Div 26, Div 27, Div 28" },
  { company: "Baker Roofing Commercial Services", sector: "Commercial Roofing & Envelope", rev: "$250M+", city: "Raleigh", state: "NC", contact: "Frank Baker", title: "Commercial Estimating VP", phone: "(919) 828-2975", email: "commercial@bakerroofing.com", status: "Active Sub Invites", trades: "Div 07, Div 08" },
  { company: "Wayne Brothers Companies", sector: "Civil, Concrete & Industrial", rev: "$180M+", city: "Davidson", state: "NC", contact: "Keith Wayne", title: "Chief Precon Officer", phone: "(704) 956-2200", email: "estimating@waynebrothers.com", status: "Active Sub Invites", trades: "Div 02, Div 03" },
  { company: "Piedmont Mechanical Commercial", sector: "Commercial Mechanical & Plumbing", rev: "$95M+", city: "Spartanburg / Charlotte", state: "NC", contact: "Charles Piedmont", title: "Precon Director", phone: "(704) 394-8844", email: "bids@piedmontmechanical.com", status: "Open to Bids", trades: "Div 22, Div 23" },
  { company: "Carolina Drywall & Acoustics Inc", sector: "Commercial Framing & Drywall", rev: "$60M+", city: "Charlotte", state: "NC", contact: "Anthony Russo", title: "VP Estimating", phone: "(704) 588-4411", email: "estimating@carolinadrywall.com", status: "Active Sub Invites", trades: "Div 09" },
  { company: "Mid-Atlantic Interior Specialists", sector: "Commercial Acoustical Ceilings & TI", rev: "$32M+", city: "Raleigh", state: "NC", contact: "Gerald Vance", title: "Estimating Manager", phone: "(919) 833-2211", email: "bids@midatlanticinteriors.com", status: "Open to Bids", trades: "Div 09, Div 08" },
  { company: "Queen City Glass & Glazing", sector: "Commercial Storefronts & Curtainwall", rev: "$45M+", city: "Charlotte", state: "NC", contact: "Robert Miller", title: "Chief Estimator", phone: "(704) 399-5500", email: "estimating@queencityglass.com", status: "Active Sub Invites", trades: "Div 08" },
  { company: "Tarheel Concrete Contractors", sector: "Commercial Cast-in-Place Concrete", rev: "$52M+", city: "Greensboro", state: "NC", contact: "Bradley Tarheel", title: "Precon VP", phone: "(336) 294-1100", email: "bids@tarheelconcrete.com", status: "Active Sub Invites", trades: "Div 03" },
  { company: "Triangle Painting & Commercial", sector: "Commercial Coatings & Wallcoverings", rev: "$24M+", city: "Raleigh", state: "NC", contact: "Marcus Triangle", title: "Estimating Lead", phone: "(919) 829-0011", email: "commercial@trianglepainting.com", status: "Open to Bids", trades: "Div 09" },
  { company: "Palmetto Commercial Flooring NC", sector: "Commercial Carpet, LVT & Tile", rev: "$28M+", city: "Charlotte", state: "NC", contact: "David Floyd", title: "Division Lead", phone: "(704) 596-7788", email: "bids@palmettoflooringnc.com", status: "Active Sub Invites", trades: "Div 09" },
  { company: "Carolina Fire Protection Commercial", sector: "Commercial Fire Sprinklers", rev: "$42M+", city: "Dunn / Raleigh", state: "NC", contact: "Scott Fire", title: "Precon Director", phone: "(910) 892-8178", email: "estimating@carolinafire.com", status: "Active Sub Invites", trades: "Div 21" },
  { company: "Custom Woodworks Commercial", sector: "Architectural Millwork & Casework", rev: "$18M+", city: "Kernersville", state: "NC", contact: "Timothy Wood", title: "Chief Estimator", phone: "(336) 996-3344", email: "bids@customwoodworksnc.com", status: "Open to Bids", trades: "Div 06, Div 12" },
  { company: "Southern Steel Fabricators NC", sector: "Structural & Miscellaneous Metals", rev: "$36M+", city: "Charlotte", state: "NC", contact: "Donald Iron", title: "Estimating VP", phone: "(704) 377-2200", email: "estimating@southernsteelncllc.com", status: "Active Sub Invites", trades: "Div 05" },
  { company: "Appalachian Commercial Tile", sector: "Hard Tile & Stone Installation", rev: "$14M+", city: "Asheville", state: "NC", contact: "Jesse Stone", title: "Estimator", phone: "(828) 254-6633", email: "jesse@appalachiantile.com", status: "Open to Bids", trades: "Div 09" },
  { company: "Coastal Masonry Systems", sector: "Commercial CMU & Brick Veneer", rev: "$26M+", city: "Wilmington", state: "NC", contact: "Henry Block", title: "Precon Manager", phone: "(910) 763-8811", email: "bids@coastalmasonrync.com", status: "Active Sub Invites", trades: "Div 04" }
];

const headers = [
  "company_name",
  "primary_sector",
  "annual_revenue_est",
  "hq_city",
  "hq_state",
  "contact_name",
  "contact_title",
  "phone",
  "email",
  "bidding_status",
  "target_trades"
];

const rows = gcs.map(gc => [
  `"${gc.company}"`,
  `"${gc.sector}"`,
  `"${gc.rev}"`,
  `"${gc.city}"`,
  `"${gc.state}"`,
  `"${gc.contact}"`,
  `"${gc.title}"`,
  `"${gc.phone}"`,
  `"${gc.email}"`,
  `"${gc.status}"`,
  `"${gc.trades}"`
].join(","));

const csvContent = [headers.join(","), ...rows].join("\n");

const targetPath = path.resolve(
  "BUSINESS-CAPITAL-DATA-ROOM/CON-001/DATA/prospects/nc_commercial_gcs.csv"
);

fs.writeFileSync(targetPath, csvContent, "utf-8");
console.log(`Successfully generated ${gcs.length} top commercial GC prospects in ${targetPath}`);
